# Generated by Django 2.1.7 on 2019-04-24 04:33

import contact_project.restconf.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', contact_project.restconf.models.ContactAppManager()),
                ('all_objects', contact_project.restconf.models.ContactAppManager(alive_only=False)),
            ],
        ),
    ]
