# Generated by Django 2.2 on 2019-05-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190515_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
