# Generated by Django 2.1.7 on 2019-04-24 04:33

import contact_project.restconf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('objects', contact_project.restconf.models.ContactAppManager()),
                ('all_objects', contact_project.restconf.models.ContactAppManager(alive_only=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', contact_project.restconf.models.ContactAppManager()),
                ('all_objects', contact_project.restconf.models.ContactAppManager(alive_only=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='membercontactnumber',
            managers=[
                ('objects', contact_project.restconf.models.ContactAppManager()),
                ('all_objects', contact_project.restconf.models.ContactAppManager(alive_only=False)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, to='groups.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
