# Generated by Django 2.1.7 on 2019-04-24 10:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190424_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercontactnumber',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='groups.Member'),
        ),
        migrations.AlterField(
            model_name='membercontactnumber',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None),
        ),
    ]
